template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "kalm1243"
__REPO__ = "lang-xal"
__UND2C__ = "xal"
__UNDEFINED__ = "Kalmyk"
__UND__ = "xal"
