template = "https://github.com/giellalt/template-lang-und"
rev_id = 346
template_sha = "f98c2a37b9866895a157f22bea282f596e7a321a"

[replacements]
__GLOTTOLOG_ID__ = "kalm1243"
__REPO__ = "lang-xal"
__UND2C__ = "xal"
__UNDEFINED__ = "Kalmyk"
__UND__ = "xal"
