[package]
name = "xal"
human_name = "Kalmyk"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.xal]
filename = "xal-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-xal"
platform = "windows"
uuid = "D4D590FB-87AD-4C76-8EEE-A8AF71134D8A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.xal"
package = "speller-xal"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-xal-mso"
platform = "windows"
uuid = "CC014535-47B6-4CF9-BF04-582EE17D641A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-xal"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
